### ISSUE TITLE
Tests fail with "director is currently processing tasks" when running BATs

### ISSUE THREAD

**Issue by dmutreja** [oracle/bosh-oracle-cpi#12]
Running a subset of BATs suite 

```bundle exec rspec ./spec/system/with_release_stemcell_deployment_spec.rb``` 

failed with

```
Failures:

  1) with release, stemcell and deployment job should recreate a job
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       director is currently processing tasks
     # ./lib/bat/requirements.rb:32:in `requirement'
     # ./spec/system/spec_helper.rb:72:in `block (2 levels) in <top (required)>'

  2) with release, stemcell and deployment job should stop and start a job
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       director is currently processing tasks
     # ./lib/bat/requirements.rb:32:in `requirement'
     # ./spec/system/spec_helper.rb:72:in `block (2 levels) in <top (required)>'

  3) with release, stemcell and deployment logs should get agent log
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       director is currently processing tasks
     # ./lib/bat/requirements.rb:32:in `requirement'
     # ./spec/system/spec_helper.rb:72:in `block (2 levels) in <top (required)>'

  4) with release, stemcell and deployment logs should get job logs
     Failure/Error: Unable to find matching line from backtrace
     RuntimeError:
       director is currently processing tasks
     # ./lib/bat/requirements.rb:32:in `requirement'
     # ./spec/system/spec_helper.rb:72:in `block (2 levels) in <top (required)>'

```

**Comment by dmutreja** [comment]
Discussed on https://cloudfoundry.slack.com/files/U5UQFUHBR/F7T1Y85RQ/Untitled.txt

**Comment by dmutreja** [comment]
Response from @cdutra https://cloudfoundry.slack.com/archives/C7P97LNFL/p1509552751000511

**Comment by dmutreja** [comment]
Recreated a director-env without health_monitor and, as expected,  no longer run encounter this issue.
  
/cc @cdutra @cppforlife
