### ISSUE TITLE
delete_vm fails to release assigned private IP

### ISSUE THREAD

**Issue by dmutreja** [oracle/bosh-oracle-cpi#4]
The issue came up during while running bosh-acceptance-tests (BATs).   One of the test failures was 

```
 1) network configuration when using manual networking changes static IP address
     Failure/Error: expect(bosh("-d #{deployment.name} deploy #{deployment.to_path}")).to succeed
     Bosh::Exec::Error:
       command '/usr/local/bin/bosh2 --non-interactive --json -d bat deploy /tmp/d20171027-23748-od7gbv/deployment 2>&1' failed with exit code 1
     # ./lib/bat/bosh_runner.rb:25:in `bosh'
     # ./lib/bat/bosh_helper.rb:14:in `bosh'
     # ./spec/system/network_configuration_spec.rb:68:in `block (3 levels) in <top (required)>'

```

Individual test can be run by executing

``` bundle exec rspec ./spec/system/network_configuration_spec.rb:73```

CPI logs on the director revealed that the failure was 
```
[VMOperations] 2017/10/27 21:16:24 DEBUG - Error creating instance [POST /instances/][400] launchInstanceBadRequest  &{Code:0xc4202e76e0 Message:0xc4202e7700}[The IP address 10.0.7.30 has already been allocated for the Subnet ocid1.subnet.oc1.phx.aaaaaaaahrtlqqmkkxur53ujq64es5l27s5vvwkcsq3rz6mnankk3yo6mqrq.]
```

Relevant sequence of calls to the CPI was 

- create_vm with private IP 10.0.7.30
- delete_vm 
- create_vm with the same IP

**Comment by dmutreja** [comment]
[cpi.stderr.log](https://github.com/oracle/bosh-oracle-cpi/files/1423567/cpi.stderr.log)
Full cpi log

**Comment by dmutreja** [comment]
` bundle exec rspec ./spec/system/with_release_stemcell_deployment_spec.rb:46` fails with the error
